### PR TITLE
Fix PHP linter

### PR DESCRIPTION
**Pull request by vitormattos**
I created this branch from https://github.com/theCalcaholic/nextcloud-secrets/pull/12

Please, first review the PR #12. If you approve the PR #12, the changed files from this PR will reduce and turn more easy to do the review.

> PS: I only fixed the linter tests.

### CODE REVIEW

**Comment by theCalcaholic** [comment]
Hey, I just wanted to thank you for these PRs. I was lately very occupied with my other project (https://nextcloudpi.com), but I'll hopefully get to them over the course of this week.

**Comment by vitormattos** [comment]
Happy Christmas and New Year to you too!

Did you speak at the last Nextcloud Conference?

Look my PR in sequence, from oldest (less ID) to newest (this PR).

**Comment by theCalcaholic** [comment]
Thank you :) The same to you!
It was James who did most of the talking, but yes, I said a few words about NCP as well :)

**Comment by theCalcaholic** [comment]
Merged on cli (I forgot to use `--no-ff`, so GH doesn't recognize it)

**Pull request closed without merging**
